# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rake', '~> 13.0'

group :development do
  gem 'climate_control', '~> 1.2'
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.56'
  gem 'rubocop-performance', '~> 1.19'
  gem 'rubocop-rspec', '~> 2.23'
  gem 'simplecov', '~> 0.22.0'
  gem 'solargraph', '~> 0.49.0'
end
