name: TypeScript CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: npm
          cache-dependency-path: typescript/package-lock.json
      - run: npm ci
      - run: npm run coverage